version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: benji
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    command:
      - --host=postgres
      - --user=benji
      - --pass=pass123
      - --db=mydb
      - --port=5432
      - --ssl=disable
